//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumano.Data.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REQUEST_FINDARTIFACT", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Request")]
    [System.SerializableAttribute()]
    public partial class REQUEST_FINDARTIFACT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TargetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Kumano.Data.Service.FINDTARGET_SELECTOR TargetTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((this.TargetIdField.Equals(value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Kumano.Data.Service.FINDTARGET_SELECTOR TargetType {
            get {
                return this.TargetTypeField;
            }
            set {
                if ((this.TargetTypeField.Equals(value) != true)) {
                    this.TargetTypeField = value;
                    this.RaisePropertyChanged("TargetType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FINDTARGET_SELECTOR", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Construction")]
    public enum FINDTARGET_SELECTOR : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CATEGORY = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RESPONSEAPI_BASE", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kumano.Data.Service.RESPONSE_GETSERVERVERSION))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kumano.Data.Service.RESPONSE_LOADTHUMBNAIL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kumano.Data.Service.RESPONSE_FINDARTIFACT))]
    public partial class RESPONSEAPI_BASE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RESPONSE_GETSERVERVERSION", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Response")]
    [System.SerializableAttribute()]
    public partial class RESPONSE_GETSERVERVERSION : Kumano.Data.Service.RESPONSEAPI_BASE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionText {
            get {
                return this.VersionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionTextField, value) != true)) {
                    this.VersionTextField = value;
                    this.RaisePropertyChanged("VersionText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RESPONSE_LOADTHUMBNAIL", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Response")]
    [System.SerializableAttribute()]
    public partial class RESPONSE_LOADTHUMBNAIL : Kumano.Data.Service.RESPONSEAPI_BASE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ThumbnailBytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ThumbnailBytes {
            get {
                return this.ThumbnailBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailBytesField, value) != true)) {
                    this.ThumbnailBytesField = value;
                    this.RaisePropertyChanged("ThumbnailBytes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RESPONSE_FINDARTIFACT", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Response")]
    [System.SerializableAttribute()]
    public partial class RESPONSE_FINDARTIFACT : Kumano.Data.Service.RESPONSEAPI_BASE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.LinkedList<Kumano.Data.Service.DataArtifact> ArtifactsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.LinkedList<Kumano.Data.Service.DataArtifact> Artifacts {
            get {
                return this.ArtifactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtifactsField, value) != true)) {
                    this.ArtifactsField = value;
                    this.RaisePropertyChanged("Artifacts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataArtifact", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Serialized")]
    [System.SerializableAttribute()]
    public partial class DataArtifact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifyKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentifyKey {
            get {
                return this.IdentifyKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifyKeyField, value) != true)) {
                    this.IdentifyKeyField = value;
                    this.RaisePropertyChanged("IdentifyKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ThumbnailKey {
            get {
                return this.ThumbnailKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailKeyField, value) != true)) {
                    this.ThumbnailKeyField = value;
                    this.RaisePropertyChanged("ThumbnailKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VERSION_SELECTOR", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Construction")]
    public enum VERSION_SELECTOR : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICE_VERSION = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATABASE_VERSION = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        API_VERSION = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REQUEST_LOADTHUMBNAIL", Namespace="http://schemas.datacontract.org/2004/07/Mogami.Service.Request")]
    [System.SerializableAttribute()]
    public partial class REQUEST_LOADTHUMBNAIL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailKey {
            get {
                return this.ThumbnailKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailKeyField, value) != true)) {
                    this.ThumbnailKeyField = value;
                    this.RaisePropertyChanged("ThumbnailKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IMogamiApiService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMogamiApiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/FindArtifact", ReplyAction="http://tempuri.org/IMogamiApiService/FindArtifactResponse")]
        Kumano.Data.Service.RESPONSE_FINDARTIFACT FindArtifact(Kumano.Data.Service.REQUEST_FINDARTIFACT reqparam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/FindArtifact", ReplyAction="http://tempuri.org/IMogamiApiService/FindArtifactResponse")]
        System.Threading.Tasks.Task<Kumano.Data.Service.RESPONSE_FINDARTIFACT> FindArtifactAsync(Kumano.Data.Service.REQUEST_FINDARTIFACT reqparam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/GetServerVersion", ReplyAction="http://tempuri.org/IMogamiApiService/GetServerVersionResponse")]
        Kumano.Data.Service.RESPONSE_GETSERVERVERSION GetServerVersion(Kumano.Data.Service.VERSION_SELECTOR versionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/GetServerVersion", ReplyAction="http://tempuri.org/IMogamiApiService/GetServerVersionResponse")]
        System.Threading.Tasks.Task<Kumano.Data.Service.RESPONSE_GETSERVERVERSION> GetServerVersionAsync(Kumano.Data.Service.VERSION_SELECTOR versionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/LoadThumbnail", ReplyAction="http://tempuri.org/IMogamiApiService/LoadThumbnailResponse")]
        Kumano.Data.Service.RESPONSE_LOADTHUMBNAIL LoadThumbnail(Kumano.Data.Service.REQUEST_LOADTHUMBNAIL reqparam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/LoadThumbnail", ReplyAction="http://tempuri.org/IMogamiApiService/LoadThumbnailResponse")]
        System.Threading.Tasks.Task<Kumano.Data.Service.RESPONSE_LOADTHUMBNAIL> LoadThumbnailAsync(Kumano.Data.Service.REQUEST_LOADTHUMBNAIL reqparam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/Login", ReplyAction="http://tempuri.org/IMogamiApiService/LoginResponse")]
        void Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMogamiApiService/Login", ReplyAction="http://tempuri.org/IMogamiApiService/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IMogamiApiService/Logout", ReplyAction="http://tempuri.org/IMogamiApiService/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IMogamiApiService/Logout", ReplyAction="http://tempuri.org/IMogamiApiService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMogamiApiServiceChannel : Kumano.Data.Service.IMogamiApiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MogamiApiServiceClient : System.ServiceModel.ClientBase<Kumano.Data.Service.IMogamiApiService>, Kumano.Data.Service.IMogamiApiService {
        
        public MogamiApiServiceClient() {
        }
        
        public MogamiApiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MogamiApiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MogamiApiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MogamiApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Kumano.Data.Service.RESPONSE_FINDARTIFACT FindArtifact(Kumano.Data.Service.REQUEST_FINDARTIFACT reqparam) {
            return base.Channel.FindArtifact(reqparam);
        }
        
        public System.Threading.Tasks.Task<Kumano.Data.Service.RESPONSE_FINDARTIFACT> FindArtifactAsync(Kumano.Data.Service.REQUEST_FINDARTIFACT reqparam) {
            return base.Channel.FindArtifactAsync(reqparam);
        }
        
        public Kumano.Data.Service.RESPONSE_GETSERVERVERSION GetServerVersion(Kumano.Data.Service.VERSION_SELECTOR versionType) {
            return base.Channel.GetServerVersion(versionType);
        }
        
        public System.Threading.Tasks.Task<Kumano.Data.Service.RESPONSE_GETSERVERVERSION> GetServerVersionAsync(Kumano.Data.Service.VERSION_SELECTOR versionType) {
            return base.Channel.GetServerVersionAsync(versionType);
        }
        
        public Kumano.Data.Service.RESPONSE_LOADTHUMBNAIL LoadThumbnail(Kumano.Data.Service.REQUEST_LOADTHUMBNAIL reqparam) {
            return base.Channel.LoadThumbnail(reqparam);
        }
        
        public System.Threading.Tasks.Task<Kumano.Data.Service.RESPONSE_LOADTHUMBNAIL> LoadThumbnailAsync(Kumano.Data.Service.REQUEST_LOADTHUMBNAIL reqparam) {
            return base.Channel.LoadThumbnailAsync(reqparam);
        }
        
        public void Login() {
            base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
    }
}
